name: Continuous Deployment

on:
  workflow_dispatch:
    inputs:
      deploy_target:
        description: 'target server'
        required: true
        type: choice
        options:
          - production

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Container Registry
        uses: docker/login-action@v2
        with:
          registry: registry.digitalocean.com/library-app-container-registry
          username: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          password: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: registry.digitalocean.com/library-app-container-registry/library-app:${{ github.sha }}

      - name: Deploy to DigitalOcean Droplet
        env:
          ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          HOST: ${{ secrets.DIGITALOCEAN_HOST }}
          USERNAME: ${{ secrets.DIGITALOCEAN_USERNAME }}
          SSH_KEY: ${{ secrets.DIGITALOCEAN_SSHKEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H $HOST >> ~/.ssh/known_hosts
          ssh $USERNAME@$HOST << EOF
            docker login -u $ACCESS_TOKEN -p $ACCESS_TOKEN registry.digitalocean.com
            docker pull registry.digitalocean.com/library-app-container-registry/library-app:${{ github.sha }}
            docker stop library-app || true
            docker rm library-app || true
            docker run -d --name library-app \
              -p 80:3000 \
              --env-file /opt/libraryapp/env/.env \
              registry.digitalocean.com/library-app-container-registry/library-app:${{ github.sha }}
          EOF
